### ISSUE TITLE
UTF-8 characters in file pathes make fgallery to hang with 100% CPU usage.

### ISSUE THREAD

**Issue by yscialom** [wavexx/fgallery#29] opened 2015-06-22 14:02 UTC
I'll provide as much information as I can in the following days; feel free to ask questions in advance.

**Comment by wavexx** [comment] 2015-06-22 14:39
On 06/22/2015 04:02 PM, Yankel Scialom wrote:
> I'll provide as much information as I can in the following days; feel free to ask questions in advance.

Just provide a sample image that makes it hang.

**Comment by yscialom** [comment] 2015-06-27 18:36
I apology for the lag, there's been a lot of cultural events in my country this week, I just turned on my computer for the first time since last monday. As for our issue, I've prepared a minimal reproduction script.
Again, feel free to ask me questions, I'll be more prompt to reply now.

## Reproduction script
```shell
# get reproduction data
mkdir -p /tmp/github.com-wavexx-fgallery-issues-29/
cd /tmp/github.com-wavexx-fgallery-issues-29/
wget -q http://www.scialom.org/issue-29.tar
tar -xf issue-29.tar 

# clone fgallery
git clone --depth 1 git://github.com/wavexx/fgallery.git

# reproduce bug
mkdir dest
dir=$(echo _*) # so I don't make you type non ASCII characters
fgallery/fgallery $dir dest/$dir
```

## My envirnment
#### GNU/Linux
linux 3.19.0-21

#### locales
```shell
$ dpkg -l locales
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version       Architecture  Description
+++-=================-=============-=============-=======================================
ii  locales           2.13+git20120 all           common files for locale support
```

```shell
$ env | grep LANG
LANG=en_US.UTF-8
GDM_LANG=fr_FR
LANGUAGE=en_US.UTF-8
```

#### bash
```shell
$ bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
```

#### Perl
```shell
$ perl --version

This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi
(with 39 registered patches, see perl -V for more detail)
```

**Comment by wavexx** [comment] 2015-06-28 18:12
Humm, I cannot reproduce it here. This looks like just a common "e" acute (U+00E9). My locale is also en_US.UTF-8 and it seems to work fine (indeed, I also have many e/a/u with accents that I normally work with without issues).

Can you tell me at which steps it hangs? (while reading, processing, generating archive...).
You can also run fgallery with -v to get extra debugging output to see if there's a subcommand that seems to hang.

**Comment by yscialom** [comment] 2015-06-29 17:54
That's strange...

```shell
$ ./issue29 
Cloning into 'fgallery'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 29 (delta 1), reused 20 (delta 0), pack-reused 0
Receiving objects: 100% (29/29), 129.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
+ cp -r /tmp/github.com-wavexx-fgallery-issues-29/fgallery/view dest/_é
reading  0%: _�.jpg
```

**Comment by yscialom** [comment] 2015-06-29 18:00
It get "curioser and curioser"... Check that:
```shell
$ cd fgallery/
$ git diff
diff --git a/fgallery b/fgallery
index 954749f..5b28e22 100755
--- a/fgallery
+++ b/fgallery
@@ -397,7 +397,7 @@ sub analyze_file
   # sanitize file name
   $base =~ s/[^\w]/_/gu;
   my $root = $base;
-  for(my $c = 0;; ++$c)
+  for(my $c = 0; $c < 666; ++$c)
   {
     my $tmp = "$out/imgs/$root.$ext";
     if(sysopen(my $fd, $tmp, O_WRONLY|O_CREAT|O_EXCL, $mode))
$ cd ..
$ fgallery/fgallery -v _é/ dest/_é/
reading completed  
+ cp _é/_é.jpg dest/_é//files/_�_665.jpg
cp: cannot create regular file ‘dest/_Ã©//files/_é_665.jpg’: No such file or directory
error: command "cp _é/_é.jpg dest/_é//files/_�_665.jpg" failed
```
```shell

**Comment by wavexx** [comment] 2015-07-02 10:58
Looking at this, it seems that $base is already corrupted by the time the filename is composed.
Can you put some print statements before/after $base +~ and see when that odd character is introduced?

**Comment by wavexx** [comment] 2015-07-18 20:45
Did you have a chance to debug it a bit further?

**Comment by yscialom** [comment] 2015-07-26 12:17
Hi, I was in vacation.
I tried to investigate what was going on with $base, (un)fortunately after I upgraded my packages, I can not reproduce the bug any more.

I guess we'll never know...

**Comment by wavexx** [comment] 2015-07-26 15:57
Happily closing™

**Closed by wavexx** 2015-07-26 15:57 UTC

**Comment by nguillaumin** [comment] 2018-12-25 10:58
Something similar is happening to me with version 1.8.2, if I have a non-ASCII character in the target folder name:

```
$ fgallery  -v photos 2018-12-Noël
+ cp -L -R /usr/share/fgallery/view 2018-12-Noël
reading  0%: 20181221_190558.jpg
```

It just hangs there at 0%. Using a different name like `2018-12-Noel` works.

**Comment by kensanata** [comment] 2019-01-01 13:16
I cannot reproduce this with [sitelen-mute](https://github.com/kensanata/sitelen-mute), so if you want to try that instead? Or perhaps: what sort of operating system are you using: could it be an issue with your filesystem? I remember that the HFS+ filesystem (e.g. macOS)  uses NFD (decomposed) for filenames so ë and e + combining ¨ result in different bytes. 

Anyway:

```
alex@melanobombus:~/src/sitelen-mute$ sitelen-mute test-in 2018-12-Noël
Image file inspection 100% completed - will now process 2 image files
Processing of 2 image files 100% completed          
Updated /home/alex/src/sitelen-mute/2018-12-Noël/files/album.zip with 2 image files
Wrote new /home/alex/src/sitelen-mute/2018-12-Noël/data.json
Wrote new /home/alex/src/sitelen-mute/2018-12-Noël/index.html
sitelen-mute version 2.0.0 created gallery in /home/alex/src/sitelen-mute/2018-12-Noël/
```

**Comment by wavexx** [comment] 2019-01-01 14:50
On Tue, Jan 01 2019, Alex Schroeder wrote:
> I cannot reproduce this with
> [sitelen-mute](https://github.com/kensanata/sitelen-mute), so if you
> want to try that instead? Or perhaps: what sort of operating system
> are you using: could it be an issue with your filesystem? I remember
> that the HFS+ filesystem (e.g. macOS) uses NFD (decomposed) for
> filenames so ë and e + combining ¨ result in different bytes.

Thinking out loud here, to help you debug.

I explicitly use LC_CTYPE as the filesystem encoding. This is mostly ok,
but only for *nix systems. This _requires_ that the appropriate LC_*
variables are set.

And yes, OSX does need special-casing. Maybe there's a decent way to get
the filesystem encoding like python's "locale" module instead of doing
so.

In theory the filesystem encoding is mostly pass-through in the code
(we'd like to keep the real filename when possible), but we need to
ensure chars can be de/encoded at least in utf-8 for json. There's a
regex that will substitute unencodable chars with ascii equivalents so
that we can do that.

Type:

env | egrep 'LANG|LC_'

to get the current locale status.

**Comment by nguillaumin** [comment] 2019-01-04 17:17
I'm running Arch Linux, on an encrypted filesystem (full disk encryption with ext4 over dm-crypt), perhaps that's the culprit?

```
$ env | egrep 'LANG|LC_'
LANG=en_US.UTF-8
GDM_LANG=en_US.UTF-8
```

I didn't know about sitelen-mute, what's the relation ship with fgallery? I tried it and it works, it doesn't get stuck when using the name `Noël`
