### ISSUE TITLE
Issue on Mac OS-X 10.11.4

### ISSUE THREAD

**Issue by haennima** [wavexx/fgallery#47] opened 2016-04-26 06:17 UTC
Hello

I have successfully installed fgallery 1.8.1 on Mac OS-X El Capitan (10.11.4)
 (brew install imagemagick lcms2 jpeg jpegoptim pngcrush fbida)
 (sudo cpan -i JSON JSON::XS Image::ExifTool)
 (export PERL5LIB=$BREWPATH/Cellar/exiftool/9.61/libexec/lib:$HOME/perl5/lib/perl5)
 (edit line 378 replace -r with -R) 

while creating a gallery I get the following error on one of the last lines of code (836)

 gallery
 reading completed                     
 processing completed                     
 generating archive...
 hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at ./fgallery line 836.

do you have any idea on what's going wrong?
Thanks for your support
best regards
Mat

**Comment by haennima** [comment] 2016-04-26 06:25
I also get the same error with "fgallery-master"

reading completed
processing completed
generating archive...
hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at ./fgallery line 849.

**Comment by wavexx** [comment] 2016-04-26 10:00
On Tue, Apr 26 2016, Mat <notifications@github.com> wrote:
> I also get the same error with "fgallery-master"
>
> reading completed
> processing completed
> generating archive...
> hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at ./fgallery line 849.

could you tell me which perl version is OSX using now?
perl --version?

And also, which version of the JSON module you have installed.

**Comment by haennima** [comment] 2016-04-26 11:41
Hello
thanks for your reply

OS-X 10.11.4 is using v5.18.2
$ perl --version
This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

JSON was installed through cpan
$ sudo cpan -i JSON
JSON is up to date (2.90).

I hope this helps

**Comment by wavexx** [comment] 2016-04-26 21:14
I have the same JSON module, but with perl 5.22. It's actually failing when generating the json, but I cannot see an obvious way that could cause \%json to be a scalar. I'll fetch some colleague with mac tomorrow to see if I can reproduce the issue.

**Comment by wavexx** [comment] 2016-04-26 21:16
As a last comment, if you run with -v, do you see images actually being processed?

**Comment by haennima** [comment] 2016-04-27 06:20
Yes images have always been processed. (Counter showing progress in %)
Just the Generation of the JSON fails. (the last step)

My Colleague Michael figured out how to produce the JSON:
replacing: print($fd encode_json(\%json));
with: print($fd JSON->new->utf8->allow_nonref->encode(\%json));

This works fine. At least on my Mac.

**Comment by wavexx** [comment] 2016-04-27 09:50
On Wed, Apr 27 2016, Mat <notifications@github.com> wrote:
> Yes images have always been processed. (Counter showing progress in %)
> Just the Generation of the JSON fails. (the last step)
>
> My Colleague Michael figured out how to produce the JSON:
> replacing: print($fd encode_json(\%json));
> with: print($fd JSON->new->utf8->allow_nonref->encode(\%json));
>
> This works fine. At least on my Mac.

I assume so, but it doesn't explain where the nonref comes from, which
I'd like to know.

Can your colleague maybe drill it down more?

None of my colleagues have 10.11 yet, and I couldn't easily find a way
to reproduce the issue.

Does it happen in all of your galleries? Maybe it's some data coming out
of exiftool itself.

**Comment by haennima** [comment] 2016-04-27 11:31
We activated the dumper (print Dumper \%json;). This is what we get as an output:

reading completed     
processing completed     
$VAR1 = {
          'blur' => [
                      600,
                      336
                    ],
          'data' => [
                      {
                        'blur' => 'blurs/IMG-1.jpg',
                        'img' => [
                                   'imgs/IMG-1.jpg',
                                   [
                                     1600,
                                     1200
                                   ]
                                 ],
                        'stamp' => 1,
                        'thumb' => [
                                     'thumbs/IMG-1.jpg',
                                     [
                                       150,
                                       113
                                     ]
                                   ]
                      },
                      {
                        'img' => [
                                   'imgs/IMG-2.jpg',
                                   [
                                     1600,
                                     1200
                                   ]
                                 ],
                        'thumb' => [
                                     'thumbs/IMG-2.jpg',
                                     [
                                       150,
                                       113
                                     ]
                                   ],
                        'stamp' => 2,
                        'blur' => 'blurs/IMG-2.jpg'
                      }
                    ],
          'thumb' => {
                       'min' => [
                                  150,
                                  112
                                ],
                       'max' => [
                                  267,
                                  200
                                ]
                     },
          'version' => '1.9'
        };
hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at ./fgallery line 853.

I took 2 new (clean) pictures, and it still happens.
Does this help?

**Comment by haennima** [comment] 2016-04-27 11:34
We activated the dumper (print Dumper \%json;). This is what we get as an output:

reading completed
processing completed
$VAR1 = {
          'blur' => [
                      600,
                      336
                    ],
          'data' => [
                      {
                        'blur' => 'blurs/IMG-1.jpg',
                        'img' => [
                                   'imgs/IMG-1.jpg',
                                   [
                                     1600,
                                     1200
                                   ]
                                 ],
                        'stamp' => 1,
                        'thumb' => [
                                     'thumbs/IMG-1.jpg',
                                     [
                                       150,
                                       113
                                     ]
                                   ]
                      },
                      {
                        'img' => [
                                   'imgs/IMG-2.jpg',
                                   [
                                     1600,
                                     1200
                                   ]
                                 ],
                        'thumb' => [
                                     'thumbs/IMG-2.jpg',
                                     [
                                       150,
                                       113
                                     ]
                                   ],
                        'stamp' => 2,
                        'blur' => 'blurs/IMG-2.jpg'
                      }
                    ],
          'thumb' => {
                       'min' => [
                                  150,
                                  112
                                ],
                       'max' => [
                                  267,
                                  200
                                ]
                     },
          'version' => '1.9'
        };
hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at ./fgallery line 853.

I took 2 new (clean) pictures, and it still happens.
Does this help?

(Sorry all the spaces/tabs are geting stripped in the output above)

**Comment by wavexx** [comment] 2016-04-28 11:07
I don't see anything wrong here. Could you try generating a gallery with just one image? And send me the image as well?

**Comment by haennima** [comment] 2016-05-02 15:11
sure.
Attached you will find the one picture and the output from the cli as a text file (to prevent the formatting)

**Comment by haennima** [comment] 2016-05-02 15:12
![hd](https://cloud.githubusercontent.com/assets/7813433/14958035/e47575d2-1088-11e6-829e-b99c04de2349.jpg)
[cli.txt](https://github.com/wavexx/fgallery/files/245334/cli.txt)

**Comment by wavexx** [comment] 2016-05-22 21:24
Duplicate of #48 

Please try with the latest sources, which should fix the issue.
Cpanel::JSON::XS is now used in place of JSON::XS.

**Comment by haennima** [comment] 2016-05-25 05:40
Cool! It works!
The latest version of fgallery fixes all problems on OS-X 10.11.4
I did no changes in my installation (JSON::XS vs. Cpanel::JSON::XS) it just works now.
Thanks a lot.
It also works on 10.11.5. (I have 2 different Macs to test...)

**Closed** 2016-05-25 06:47 UTC
